name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the Angular application
      - name: Build Angular App
        run: npm run build --prod

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: "13.60.91.157"
          EC2_USER: "ubuntu"
          EC2_KEY: "MIIEogIBAAKCAQEAqObSDDaF7nzd0VTYuaYiXUBDRwUthd8bkq9fuYaIiNrVBr+gxRWOzvIsoJMpJCtHERjspMJriUIApKM8fziUctIBL7Y9GFXp7UgsIKIWuJ5q/GaBdGHqA2DuxvLOAPkW/tPz5tCgmSXJS7cMytMrYNtDt+/pfiOccnEnJPGE+qMym/PqMqgfNu5I5A5zIcRamQWDKuS/uOymqvRXGxdWxqAOikqT1MhRPvQMfoUIOn7wELZR7v6S99Ho77+lL0yLBcLhFcyBB9DluMVY1A4LNP0zXW1q3rCRcKe8OJiej+UjN2W09+nPX2YYveVOXZD/TkvYvhCd5fNQD/fn0de1VQIDAQABAoIBADwNHR9Uf1fks2UK2qdfBxbKk2D72Uygn4gOrGUlDQRDcbwdg8auvICdn/pTeCww6uqMRw7pRRyfB+WBWDAPaNBOFDfnfl9ZpHtFztKnbpajVHx64YoEihQ7cYnwqAe2iFN//lbRVFg/FAvEgFrYq7KbIr+SIB1GAgi6bGV5LYOC0MyPHe4Kj1Gweew3z+Qhr6pO3noeKUDkxjj2efCoNUbu90HP7RRvDP9/K+lxWAyN2UyNkIu5vyP+Kz66MdmICp3E4a5hHWwOxpyC0lHcVYuSWWmLgHQHZ48c/DV1l7RYdZUfHqk5KRbjCQYYT15N6Rkbw8GVtysRbbGfMNk1TiECgYEA0WoB0TNJxaO7Um5EGoDizo8lfsjxBxTk/w+fuvIhKa3Fpb5x+bR/9zJinLOUpvOv+uJnmgbed1AdW6GQZ+kUX5Q+MHCWT6ziALE/BM2VT7g407GO9Koc2mJY359mSgfCCK4AFoe1QJ+MGq9mgS2KYrw1Y16M+5DPnuVRDV68j10CgYEAznmoEG/r4xH5726Y2aJkD0kCbf9Zzh550NThxIBkS82f+CFuHA+w++BgwBZhq0A3sfL7Jx8Wo5W3e5iXoND+Nqbi0ZdqKW6TPJQxbNvNof0GxCgNVLC0rfbYd0vt/c3Hm4vtWbO4Yg4hS/j4Ax1Ev2i8SBJAOQRTdvKh0Pa5dlkCgYAS9uWpO1rP8i7xnRi/ybJAgIglvi7NtF+0lYaimHDWZG1EwEV0FpuMGF0D0eOBZwolz0EQmtSku3WdKbl5H4t/yF4FZvzFxGNHKsYJOlDuQkGrMiY/E/S+9i8UOUw7Ig65WICbibipXImElSPUSPqCTIcNM6/SzF9xBVVcv5qV5QKBgGMRYj9IxEC2PlrQkQxTa3keCclnbNqGKuK1UgIrrHPmnGu89o0GRmAEH8fqtUAq1s5ODI2P0Bf7XQczhwVFYcQtPMVdxjVM9d5qKHDX4gloU1fI8+R/yKFzwBc1WmKd2rlaYS7aGY0KxJUkRzOPVo4Uncpi32e8GKQI9PVDfGc5AoGACgtZH2QUGEnIxiWJEhyYiYxNR8FhWfykPOUwlyFnqEuFolW8B8URhctUcYv/4aSUn0rB6uKiNRM1do/lr9RryBdfK7qYhwnPxHdpJOKQgtNWCow1S5TEMJjBPvv1LwkjstnCW7Iv+1oFOhVA87lCa435vEGgBqssB5WyF+lSfXQ="
          TARGET_DIR: /var/www/html
        run: |
          echo $EC2_HOST
          echo $EC2_USER
          echo $EC2_KEY
          # Create a temporary directory for the build files
          tar -czf dist.tar.gz -C dist/unitsource .
          
          # Copy build files to EC2
          scp -i $EC2_KEY dist.tar.gz $EC2_USER@$EC2_HOST:/tmp/
          
          # Connect to EC2, extract files, and set permissions
          ssh -i $EC2_KEY $EC2_USER@$EC2_HOST << 'EOF'
            sudo rm -rf $TARGET_DIR/*
            sudo tar -xzf /tmp/dist.tar.gz -C $TARGET_DIR
            sudo chown -R nginx:nginx $TARGET_DIR
            sudo systemctl restart nginx
          EOF