name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the Angular application
      - name: Build Angular App
        run: npm run build --prod

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          TARGET_DIR: /var/www/html
        run: |
          # Save the private key to a file
          echo "$EC2_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

          # Copy the build files to a temporary directory on the EC2 instance
          scp -i ec2-key.pem -o StrictHostKeyChecking=no -r dist/* $EC2_USER@$EC2_HOST:/tmp/dist/

          # SSH into the EC2 instance to move files and set permissions
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            # Remove existing files in the target directory
            sudo rm -rf $TARGET_DIR/*

            # Move the new build files from the temporary directory to the target directory
            sudo mv /tmp/dist/* $TARGET_DIR/

            # Set the correct ownership for the files
            sudo chown -R www-data:www-data $TARGET_DIR

            # Restart the web server to apply changes
            sudo systemctl restart nginx
          "