name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Use Node.js v16 for Angular 12 compatibility 

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npx ng build --prod  # Use npx to run Angular CLI locally

      - name: Run tests
        run: npx ng test  # Use npx for tests as well
